### PR TITLE
Add ability to expand/collapse posts summary

### PR DESCRIPTION
**Pull request by oraby**
The first commit adds the ability to expand a long post summary by clicking on an empty space in the post and collapses it on clicking on an empty space again.
The second commit adds a small link at the top of the page that expands or collapses all the posts in the page.

My javascript and jquery knowledge are limited, so apologies if some stuff aren't done in an idiomatic way.

### CODE REVIEW

**Comment by CyberShadow** [comment]
- The "expand posts [+]" button looks out of place, if we want to have one then we need to think about how to fit it into the existing design.
- No comment on the tap-to-expand functionality - if you find it useful then I don't mind having it.
- I'm thinking on whether we can solve the problem some other way, e.g. by removing more columns in narrow views. For example, the "Last post" column could go from the forum index, and same for either (or both) of "Last post" and "Replies" in the group view.

**Comment by oraby** [comment]
> The "expand posts [+]" button looks out of place, if we want to have one then we need to think about how to fit it into the existing design.

Any ideas?. Maybe we can add it in the settings page to have a checkbox that says e.g:
`[ ] Don't truncate long posts summaries`
Or you prefer to have it in the main page to remove the need to go to the settings page?

> No comment on the tap-to-expand functionality - if you find it useful then I don't mind having it.

I think it's nice non-intrusive addition without much added cost.

> I'm thinking on whether we can solve the problem some other way, e.g. by removing more columns in narrow views. For example, the "Last post" column could go from the forum index, and same for either (or both) of "Last post" and "Replies" in the group view.

That could work as well. Although I personally find these 2 columns beneficial and I prefer not to lose them in narrower views. This is not a strong opinion though and don't mind going with it if you think it's a better approach.

> Another idea (which would be good to have anyway, but might also help this particular problem) is to have a font size setting in the forum settings.

It's a god idea indeed generally, however for this issue I think that it might work e.g  for mid-sized post-summaries but not long ones.

**Comment by CyberShadow** [comment]
> Maybe we can add it in the settings page to have a checkbox

That works.

> Or you prefer to have it in the main page to remove the need to go to the settings page?

I'd actually prefer it the other way, and avoid clutter unless necessary.

**Comment by CyberShadow** [comment]
For the front page, we had some extra room for the group descriptions, so I pushed a fix to utilize it.

**Comment by CyberShadow** [comment]
Pushed another CSS tweak to shrink the auxiliary columns for the default group view.

**Comment by CyberShadow** [comment]
Maybe we should just have two rows for the thread titles in narrow views.

**Comment by oraby** [comment]
> For the front page, we had some extra room for the group descriptions, so I pushed a fix to utilize it.

> Pushed another CSS tweak to shrink the auxiliary columns for the default group view.

I like the changes :+1: 

> Maybe we should just have two rows for the thread titles in narrow views.

How about we do this and also leave the tap-to-expand part? In such way the 2-lines should be sufficient for most of the cases while extra long titles or descriptions can be easily extended on need basis.

**Pull request closed without merging**
