### PR TITLE
no more forced quoting

### PR DESCRIPTION
**Pull request by burner**
http://forum.dlang.org/post/bgevxpeyhxlplqystefm@forum.dlang.org

### CODE REVIEW

**Comment by CyberShadow** [comment]
No, for the reasons explained by the software. Quoting is an integral part of netiquette. By not quoting at least a little to indicate which post you're replying to, you're being rude to people who don't use the same software / view mode as you.

**Comment by burner** [comment]
I have to disagree. https://tools.ietf.org/html/rfc1855 3.1.3 stats that
> Content of a follow-up post should exceed quoted content.

quoting myself so I don't have to retype.
> this [quoting] feature is just poisonous for the discussion culture of this forum. Everybody is just trying to disprove the other without actually trying to bring the discussion/D forward.

Who about a linter testing that "new text.length > quote.length"

**Comment by CyberShadow** [comment]
There already is one. See the overquoting linter.

**Comment by burner** [comment]
the ratio is 1 unquoted to 4 quoted. Are you open to changing that to 4 to 1 or at least >1 to 1

**Comment by CyberShadow** [comment]
That would likely be too annoying without being useful enough. You can write a useful, coherent reply to something that is longer than your reply, without there being a sensible way to split up the part you're replying to. There's also the question of what would "fix it for me" do in this situation.

I spent some time tweaking the algorithms using existing forum posts as reference, and I'm pretty happy with how they are now.

Also...

> this [quoting] feature is just poisonous for the discussion culture of this forum. Everybody is just trying to disprove the other without actually trying to bring the discussion/D forward.

Honestly, I think you're just pulling that out of thin air. My email client quotes messages I reply to, that doesn't mean it's inviting me to be toxic towards the person I'm replying to.

**Pull request closed without merging**
