### PR TITLE
Fix #79 - Redesign forum group index to be mobile friendly

### LINKED ISSUE #79: Don't truncate forum titles, use multiple lines instead
http://forum.dlang.org/thread/swpcthmrynlcuuuzawqg@forum.dlang.org

### PR DESCRIPTION
**Pull request by ahmetsait**
Redesign:

image

### CODE REVIEW

**Comment by ahmetsait** [comment]
And this is how it looks on desktop:

image


Thoughts?

**Comment by PetarKirov** [comment]
Some of the things I like about your proposal on mobile:
* No more table view - although I'm quite used to the old design by now, I think the new design make better use of the available space
* Thread titles are fully visible (or at least not cut off as early)
* Avatars of post authors
* Better create thread button
* Date of first post is displayed

Things I think need some improvement:
* In the current design it's quite clear that the forum title and last post are clickable links, but in the new design it's not clear that the "Last Post" is a link.

**Comment by ahmetsait** [comment]
> In the current design it's quite clear that the forum title and last post are clickable links, but in the new design it's not clear that the "Last Post" is a link.

I think this is the least of our worries.

> While on mobile, having the number of post be in the middle seems fine, I think it looks awkward on desktop.

I understand that the design doesn't look so hot but my main point was to fix this mess:
D Forum Mobile

I thought about copying the discourse design but that hides a lot of information so I don't like that either.
I need a bit more actionable feedback to get somewhere with this PR so maybe suggest some adjustments on how it should look?
I will be asking for feedback on the forum as well.

**Comment by CyberShadow** [comment]
I guess this is obsoleted by #142.

**Pull request closed without merging**
